name: Build Website

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: 'pages'
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Configure Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Install Dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build
              env:
                  VITE_APIURL_BASE: ${{secrets.VITE_APIURL_BASE}}
                  VITE_API_PREFIX: ${{secrets.VITE_API_PREFIX}}

            - name: Configure GitHub Pages
              uses: actions/configure-pages@v5

            - name: Upload build for Pages
              uses: actions/upload-pages-artifact@v3
              with:
                  path: dist

    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
